/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.3.9.3 at Mon Sep 23 00:35:29 2019. */

#include "test.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif



const pb_field_t Info_fields[3] = {
    PB_FIELD(  1, INT32   , SINGULAR, STATIC  , FIRST, Info, type, type, 0),
    PB_FIELD(  2, STRING  , SINGULAR, STATIC  , OTHER, Info, data, type, 0),
    PB_LAST_FIELD
};


/* @@protoc_insertion_point(eof) */
